export const GET_IMAGE_DETAILS = '@ImageDatails/GET_IMAGE_DETAILS';
export const GET_IMAGE_DETAILS_SUCCESS = '@ImageDatails/GET_IMAGE_DETAILS_SUCCESS';
export const GET_IMAGE_DETAILS_ERROR = '@ImageDatails/GET_IMAGE_DETAILS_ERROR';
